### PR TITLE
Motor fixes

### PR DESCRIPTION
**Pull request by coxy90**
motor idle = 0 fix

### CODE REVIEW

**Comment by xd009642** [comment]
You're getting more stringent code reviews from now on

**Comment by RootCNC** [comment]
Get on the Hype train

**Comment by xd009642** [comment]
Good talk

**Comment by RootCNC** [comment]
Any time

**Comment by xd009642** [comment]
Pleasure working with you

**Comment by RootCNC** [comment]
Do you wanna play a game?

**Comment by xd009642** [comment]
Like pong?

**Comment by RootCNC** [comment]
yerh, like Pong - Ping

**Comment by xd009642** [comment]
Okay i'm now getting a ton of emails from this :laughing: lets stop

**Comment by RootCNC** [comment]
Are you? - I'm not GGGGGGG

**Comment by RootCNC** [comment]
So tell me more about this problem....

**Comment by xd009642** [comment]
Well @RootCNC basically after a long period of half after initial spin the rings don't re-spin and it's likely something in the simulink. So that's what we're working on

**Pull request merged**
